[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
name = "sthali-crud"
version = "0.0.3.6"
authors = [{ name = "Jhunu Fernandes", email = "jhunu.fernandes@gmail.com" }]
description = "A FastAPI package for CRUD operations"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "fastapi >= 0.111.1",
  "pydantic >= 2.8.2",
  "pyyaml",
  "sthali-db",
]

[project.optional-dependencies]
dev = [
  "ruff >= 0.5.2",
  "coverage",
  "httpx",
]
tests = ["coverage", "httpx"]
stage = ["build", "coverage", "uvicorn"]

[project.urls]
"Homepage" = "https://github.com/jhunufernandes/sthali-crud"
"Bug Tracker" = "https://github.com/jhunufernandes/sthali-crud/issues"

[tool.coverage.run]
branch = true
command_line = "-m unittest discover -v -s tests/"

[tool.coverage.report]
omit = [
  "tests/*",
  "sthali_db/*",
]
show_missing = true

[tool.ruff]
line-length = 119
exclude = [
  "tests/*",
  "sthali_db/*",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN401",  # any-type
  "TID252",  # relative-imports
  # "ANN002",  # missing-type-args
  # "ANN003",  # missing-type-kwargs
  # "ANN101",  # missing-type-self
  # "ANN102",  # missing-type-cls
  # "COM812",  # missing-trailing-comma
  # "D107",  # undocumented-public-init
  # "ISC001",  # single-line-implicit-string-concatenation
]

[tool.ruff.lint.per-file-ignores]
"src/sthali_crud/config.py" = [
  "UP007",  # non-pep604-annotation
]
"tests/*" = [
  "COM812",  # missing-trailing-comma
  "D100",  # undocumented-public-module
  "D101",  # undocumented-public-class
  "D102",  # undocumented-public-method
  "D104",  # undocumented-public-package
  "D106",  # undocumented-public-nested-class
  "PGH003",  # blanket-type-ignore
  "PIE804",  # unnecessary-dict-kwargs
  "PT009",  # pytest-unittest-assertion
  "PT027",  # pytest-unittest-raises-assertion
  "S101",  # assert
]

[tool.ruff.lint.pydocstyle]
convention = "google"
